function name = FRAP_naming(bname,fan,tyvec,ncon)

% This function generates the name of a FRAP file. It can be used to
% generate filenames to read as well as for saving

% INPUTS:
% bname - base name for the file
% fan - the focal adhesion number the name is for
% tyvec - type vector containing information regarding whether the polygon
%       is for the background, a control, or a bleached polygon
% ncon -  the number of control polygons for a given movie

% OUTPUTS:
% name - the name generated by the function

%Determine type of image
type = tyvec(fan);
switch type
    case 1
        pre='poly_FRAP_con_';
    case 2
        pre='poly_FRAP_blch_';
    case 0 
        pre='poly_FRAP_bkg_';
end

%Remove extensions
ppos=strfind(lower(bname),'.tif');
tname=bname(1:ppos(1)-1);

%Determine the nimber of FA
if type == 1 
    num=num2str(fan-2);
elseif type == 2 
    num=num2str(fan-ncon-2);
else
    num='0';
end

%construct the name
name=[pre tname '_' num '.dat'];

end